SELECT 
    T1.NAME AS Job_name, 
    T3.NAME AS Job_transform
FROM R_JOB AS T1
JOIN R_JOB_HOP AS T2 
    ON T1.ID_JOB = T2.ID_JOB
JOIN R_JOBEN AS T3 
    ON T2.ID_JOBEN_COPY = T3.ID_JOBEN
WHERE T3.NAME IN (
    SELECT NAME 
    FROM R_JOB
);
