SELECT DISTINCT
    t.NAME, 
    j.NAME AS JOB, 
    CAST(ja_d.VALUE_STR AS VARCHAR(255)) AS DIR_PATH, 
    d.DIRECTORY_NAME,
    db.ID_DATABASE, 
    db.NAME, 
    db.ID_TYPE, 
    db.ID_CONTYPE, 
    db.HOST_NAME, 
    CAST(db.DATABASE_NAME AS VARCHAR(255)) AS DATABASE_NAME, 
    db.PORT, 
    db.USERNAME, 
    db.PASSWORD, 
    db.SERVERNAME, 
    db.DATA_TBS, 
    db.INDEX
--  , d2.*
FROM R_T t (NOLOCK)
JOIN R_JOBEN ja (NOLOCK) 
    ON ja.CODE = 'name' 
    AND CAST(ja.VALUE_STR AS VARCHAR(50)) = t.NAME
JOIN R_JOBEB_ATT ja_d (NOLOCK) 
    ON ja.ID_JOBEN = ja_d.ID_JOBEN 
    AND ja_d.CODE = 'dir_path'
JOIN R_JOB j (NOLOCK) 
    ON j.ID_JOB = ja.ID_JOB
JOIN R_DIRECTORY d (NOLOCK) 
    ON d.ID_DIRECTORY = j.ID_DIRECTORY
JOIN R_DATABASE st (NOLOCK) 
    ON st.ID_TRANSF = t.ID_TRANSF
JOIN R_DATABASE db (NOLOCK) 
    ON db.ID_DATABASE = st.ID_DATABASE
JOIN R_DIRECTORY d2 (NOLOCK) 
    ON t.ID_DIRECTORY = d.ID_DIRECTORY
-- WHERE j.NAME = 'Job_Load'
--   AND d.DIRECTORY_NAME = 'CB_R'
-- ORDER BY 1, 4

UNION ALL

SELECT 
    T3.NAME, 
    T1.NAME, 
    NULL, 
    NULL, 
    T5.*
FROM R_JOB AS T1
JOIN R_JOB_HOP AS T2 
    ON T1.ID_JOB = T2.ID_JOB
JOIN R_JOB AS T3 
   
